version: '2'
services:
    mainsite-app:
        image: mainsite
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mainsite-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mainsite
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mainsite-mongodb:
        extends:
            file: mongodb.yml
            service: mainsite-mongodb
